<a href="https://colab.research.google.com/github/08vivek08/data-science/blob/main/1_basic_numpy_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## BASIC FUNCTION

In [ ]:
import numpy as np

In [ ]:
arr=np.arange(10000000)

In [ ]:
pylist=list(range(10000000))

In [ ]:
%time for _ in range(10): [item *3 for item in pylist]

CPU times: user 6.47 s, sys: 1.58 s, total: 8.05 s
Wall time: 8.05 s


In [ ]:
%time for _ in range(10): arr=arr*3

CPU times: user 188 ms, sys: 5.93 ms, total: 194 ms
Wall time: 193 ms


In [ ]:
array1=np.array([[4,2,15],[3,9,7]])
print(array1)

[[ 4  2 15]
 [ 3  9  7]]


In [ ]:
array1.shape

(2, 3)

In [ ]:
array1.dtype

dtype('int64')

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
# initilise all value to 0
np.zeros((4,6))          

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.zeros((4,6)).dtype

dtype('float64')

In [ ]:
array1*array1

array([[ 16,   4, 225],
       [  9,  81,  49]])

In [ ]:
array1**array1

array([[               256,                  4, 437893890380859375],
       [                27,          387420489,             823543]])

In [ ]:
1/array1

array([[0.25      , 0.5       , 0.06666667],
       [0.33333333, 0.11111111, 0.14285714]])

## SLICING

In [ ]:
array2=np.array([5,4,64,3,3,3])

In [ ]:
arr1=array2[4:6]
arr2=array2[4:6].copy()

In [ ]:
print(arr1)
print(arr2)

[3 3]
[3 3]


In [ ]:
arr1[0]=9
arr2[0]=7

In [ ]:
print(arr1)
print(arr2)

[9 3]
[7 3]


In [ ]:
array2

array([ 5,  4, 64,  3,  9,  3])

In [ ]:
a=array1
a

array([[ 4,  2, 15],
       [ 3,  9,  7]])

In [ ]:
#add corresponding column
a.sum(axis=0)

array([ 7, 11, 22])

In [ ]:
#add corresponding row
a.sum(axis=1)

array([21, 19])

In [ ]:
b=np.array([[1,2,3],[2,1,0]])

In [ ]:
##dot product of matrices 
##(2*3) . (3*2)=(2*2)np.dot
(a,b.transpose())

(array([[ 4,  2, 15],
        [ 3,  9,  7]]), array([[1, 2],
        [2, 1],
        [3, 0]]))

In [ ]:
dir(np)   #all numpy functions

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_distributor_init',
 '_global

In [ ]:
len(dir(np))

620

In [ ]:
np.cross(a,b)  #cross product

array([[-24,   3,   6],
       [ -7,  14, -15]])

In [ ]:
a

array([[ 4,  2, 15],
       [ 3,  9,  7]])

In [ ]:
np.sort(a)

array([[ 2,  4, 15],
       [ 3,  7,  9]])

In [ ]:
np.sort(a,axis=0)

array([[ 3,  2,  7],
       [ 4,  9, 15]])

In [ ]:
#a is unchanged sort function just return sorted array
a

array([[ 4,  2, 15],
       [ 3,  9,  7]])

In [ ]:
#we can explicitly change sorting algo (optional)
a=np.sort(a,axis=0,kind='quicksort')

In [ ]:
a

array([[ 3,  2,  7],
       [ 4,  9, 15]])

In [ ]:
#arange function initalises array from 0 to n-1
a=np.arange(6)

In [ ]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
b=np.array([5,5,7,9,7,13,6,6,14,63,74,41])
b.shape

(12,)

In [ ]:
b

array([ 5,  5,  7,  9,  7, 13,  6,  6, 14, 63, 74, 41])

In [ ]:
b=b.reshape(4,3)

In [ ]:
b

array([[ 5,  5,  7],
       [ 9,  7, 13],
       [ 6,  6, 14],
       [63, 74, 41]])

In [ ]:
b=b.reshape(1,12)

In [ ]:
b

array([[ 5,  5,  7,  9,  7, 13,  6,  6, 14, 63, 74, 41]])

In [ ]:
#return indices of sorted array
np.argsort(b)

array([[ 0,  1,  6,  7,  2,  4,  3,  5,  8, 11,  9, 10]])

In [ ]:
np.argmin(b)

0

In [ ]:
np.argmax(b)

10