<a href="https://colab.research.google.com/github/08vivek08/data-science/blob/main/basic_numpy_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## BASIC FUNCTION

In [122]:
import numpy as np

In [123]:
arr=np.arange(10000000)

In [124]:
pylist=list(range(10000000))

In [125]:
%time for _ in range(10): [item *3 for item in pylist]

CPU times: user 6.43 s, sys: 1.63 s, total: 8.06 s
Wall time: 8.07 s


In [126]:
%time for _ in range(10): arr=arr*3

CPU times: user 165 ms, sys: 2.85 ms, total: 168 ms
Wall time: 168 ms


In [127]:
array1=np.array([[4,2,15],[3,9,7]])
print(array1)

[[ 4  2 15]
 [ 3  9  7]]


In [128]:
array1.shape

(2, 3)

In [129]:
array1.dtype

dtype('int64')

In [130]:
np.zeros(4)

array([0., 0., 0., 0.])

In [131]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [132]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [133]:
np.zeros((4,6)).dtype

dtype('float64')

In [134]:
array1*array1

array([[ 16,   4, 225],
       [  9,  81,  49]])

In [135]:
array1**array1

array([[               256,                  4, 437893890380859375],
       [                27,          387420489,             823543]])

In [136]:
1/array1

array([[0.25      , 0.5       , 0.06666667],
       [0.33333333, 0.11111111, 0.14285714]])

## SLICING

In [137]:
array2=np.array([5,4,64,3,3,3])

In [138]:
arr1=array2[4:6]
arr2=array2[4:6].copy()

In [139]:
print(arr1)
print(arr2)

[3 3]
[3 3]


In [140]:
arr1[0]=9
arr2[0]=7

In [141]:
print(arr1)
print(arr2)

[9 3]
[7 3]


In [142]:
array2

array([ 5,  4, 64,  3,  9,  3])

In [143]:
a=array1
a

array([[ 4,  2, 15],
       [ 3,  9,  7]])

In [144]:
a.sum(axis=0)

array([ 7, 11, 22])

In [145]:
a.sum(axis=1)

array([21, 19])

In [146]:
b=np.array([[1,2,3],[2,1,0]])

In [147]:
np.dot(a,b.transpose())

array([[53, 10],
       [42, 15]])

In [148]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_distributor_init',
 '_global

In [149]:
len(dir(np))

620

In [150]:
np.cross(a,b)

array([[-24,   3,   6],
       [ -7,  14, -15]])

In [151]:
a

array([[ 4,  2, 15],
       [ 3,  9,  7]])

In [155]:
np.sort(a)

array([[ 2,  4, 15],
       [ 3,  7,  9]])

In [153]:
np.sort(a,axis=0)

array([[ 3,  2,  7],
       [ 4,  9, 15]])

In [154]:
a

array([[ 4,  2, 15],
       [ 3,  9,  7]])

In [157]:
a=np.sort(a,axis=0,kind='quicksort')

In [158]:
a

array([[ 3,  2,  7],
       [ 4,  9, 15]])

In [159]:
a=np.arange(6)

In [160]:
a

array([0, 1, 2, 3, 4, 5])

In [164]:
b=np.array([5,5,7,9,7,13,6,6,14,63,74,41])
b.shape

(12,)

In [165]:
b

array([ 5,  5,  7,  9,  7, 13,  6,  6, 14, 63, 74, 41])

In [166]:
b=b.reshape(4,3)

In [167]:
b

array([[ 5,  5,  7],
       [ 9,  7, 13],
       [ 6,  6, 14],
       [63, 74, 41]])

In [168]:
b=b.reshape(1,12)

In [169]:
b

array([[ 5,  5,  7,  9,  7, 13,  6,  6, 14, 63, 74, 41]])

In [170]:
np.argsort(b)

array([[ 0,  1,  6,  7,  2,  4,  3,  5,  8, 11,  9, 10]])

In [171]:
np.argmin(b)

0

In [172]:
np.argmax(b)

10